FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3.10 \
    python3.10-dev \
    python3-pip \
    git \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3.10 /usr/bin/python
RUN python -m pip install --upgrade pip

WORKDIR /app

COPY requirements.base.txt .

# 关键：先装 torch cu121
RUN pip install torch==2.8.0 --index-url https://download.pytorch.org/whl/cu121

# 再装其他依赖
RUN pip install --no-cache-dir -r requirements.base.txt