syntax = "proto3";

package embedding;

service EmbeddingService {
  rpc Encode(EncodeRequest) returns (EncodeResponse) {}
  rpc Similarity(CreateSimilarityRequest) returns (CreateSimilarityResponse) {}
}

message EncodeRequest {
  repeated string sentences = 1;
}

message EncodeResponse {
  repeated float embeddings = 1 [packed=true];
  int32 embedding_dim = 1024;
}

message CreateSimilarityRequest {
  string model = 1;
  string source_sentence = 2;
  repeated string sentences = 3;
}

message SimilarityResult {
  string sentence = 1;
  float similarity = 2;
}

message CreateSimilarityResponse {
  repeated SimilarityResult results = 1;
}