# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'embedding_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x65mbedding_service.proto\x12\tembedding\"\"\n\rEncodeRequest\x12\x11\n\tsentences\x18\x01 \x03(\t\"@\n\x0e\x45ncodeResponse\x12\x16\n\nembeddings\x18\x01 \x03(\x02\x42\x02\x10\x01\x12\x16\n\rembedding_dim\x18\x80\x08 \x01(\x05\"T\n\x17\x43reateSimilarityRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\x17\n\x0fsource_sentence\x18\x02 \x01(\t\x12\x11\n\tsentences\x18\x03 \x03(\t\"8\n\x10SimilarityResult\x12\x10\n\x08sentence\x18\x01 \x01(\t\x12\x12\n\nsimilarity\x18\x02 \x01(\x02\"H\n\x18\x43reateSimilarityResponse\x12,\n\x07results\x18\x01 \x03(\x0b\x32\x1b.embedding.SimilarityResult2\xac\x01\n\x10\x45mbeddingService\x12?\n\x06\x45ncode\x12\x18.embedding.EncodeRequest\x1a\x19.embedding.EncodeResponse\"\x00\x12W\n\nSimilarity\x12\".embedding.CreateSimilarityRequest\x1a#.embedding.CreateSimilarityResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENCODERESPONSE'].fields_by_name['embeddings']._loaded_options = None
  _globals['_ENCODERESPONSE'].fields_by_name['embeddings']._serialized_options = b'\020\001'
  _globals['_ENCODEREQUEST']._serialized_start=38
  _globals['_ENCODEREQUEST']._serialized_end=72
  _globals['_ENCODERESPONSE']._serialized_start=74
  _globals['_ENCODERESPONSE']._serialized_end=138
  _globals['_CREATESIMILARITYREQUEST']._serialized_start=140
  _globals['_CREATESIMILARITYREQUEST']._serialized_end=224
  _globals['_SIMILARITYRESULT']._serialized_start=226
  _globals['_SIMILARITYRESULT']._serialized_end=282
  _globals['_CREATESIMILARITYRESPONSE']._serialized_start=284
  _globals['_CREATESIMILARITYRESPONSE']._serialized_end=356
  _globals['_EMBEDDINGSERVICE']._serialized_start=359
  _globals['_EMBEDDINGSERVICE']._serialized_end=531
# @@protoc_insertion_point(module_scope)
