# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mem_pb2 as mem__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mem_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetActiveInteractionMemory = channel.unary_unary(
                '/mem.MemoryService/GetActiveInteractionMemory',
                request_serializer=mem__pb2.MemRequest.SerializeToString,
                response_deserializer=mem__pb2.MemResponse.FromString,
                _registered_method=True)
        self.GetICanMemory = channel.unary_unary(
                '/mem.MemoryService/GetICanMemory',
                request_serializer=mem__pb2.MemRequest.SerializeToString,
                response_deserializer=mem__pb2.MemResponse.FromString,
                _registered_method=True)
        self.GetAgentAllMemory = channel.unary_unary(
                '/mem.MemoryService/GetAgentAllMemory',
                request_serializer=mem__pb2.MemRequest.SerializeToString,
                response_deserializer=mem__pb2.MemResponse.FromString,
                _registered_method=True)
        self.GetChildAllMemory = channel.unary_unary(
                '/mem.MemoryService/GetChildAllMemory',
                request_serializer=mem__pb2.MemRequest.SerializeToString,
                response_deserializer=mem__pb2.MemResponse.FromString,
                _registered_method=True)
        self.GetRelateMemory = channel.unary_unary(
                '/mem.MemoryService/GetRelateMemory',
                request_serializer=mem__pb2.MemRequest.SerializeToString,
                response_deserializer=mem__pb2.MemResponse.FromString,
                _registered_method=True)


class MemoryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetActiveInteractionMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetICanMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentAllMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChildAllMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRelateMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetActiveInteractionMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveInteractionMemory,
                    request_deserializer=mem__pb2.MemRequest.FromString,
                    response_serializer=mem__pb2.MemResponse.SerializeToString,
            ),
            'GetICanMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetICanMemory,
                    request_deserializer=mem__pb2.MemRequest.FromString,
                    response_serializer=mem__pb2.MemResponse.SerializeToString,
            ),
            'GetAgentAllMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentAllMemory,
                    request_deserializer=mem__pb2.MemRequest.FromString,
                    response_serializer=mem__pb2.MemResponse.SerializeToString,
            ),
            'GetChildAllMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChildAllMemory,
                    request_deserializer=mem__pb2.MemRequest.FromString,
                    response_serializer=mem__pb2.MemResponse.SerializeToString,
            ),
            'GetRelateMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRelateMemory,
                    request_deserializer=mem__pb2.MemRequest.FromString,
                    response_serializer=mem__pb2.MemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mem.MemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mem.MemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetActiveInteractionMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mem.MemoryService/GetActiveInteractionMemory',
            mem__pb2.MemRequest.SerializeToString,
            mem__pb2.MemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetICanMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mem.MemoryService/GetICanMemory',
            mem__pb2.MemRequest.SerializeToString,
            mem__pb2.MemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentAllMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mem.MemoryService/GetAgentAllMemory',
            mem__pb2.MemRequest.SerializeToString,
            mem__pb2.MemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChildAllMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mem.MemoryService/GetChildAllMemory',
            mem__pb2.MemRequest.SerializeToString,
            mem__pb2.MemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRelateMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mem.MemoryService/GetRelateMemory',
            mem__pb2.MemRequest.SerializeToString,
            mem__pb2.MemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
