# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mem.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'mem.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmem.proto\x12\x03mem\"\xb2\x01\n\nMemRequest\x12\x10\n\x08\x63hild_id\x18\x01 \x01(\t\x12\x12\n\nchild_name\x18\x02 \x01(\t\x12\x15\n\x08\x61gent_id\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05query\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06intent\x18\x05 \x01(\tH\x02\x88\x01\x01\x12\x12\n\x05limit\x18\x06 \x01(\x05H\x03\x88\x01\x01\x42\x0b\n\t_agent_idB\x08\n\x06_queryB\t\n\x07_intentB\x08\n\x06_limit\":\n\x0bMemResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\t2\xaa\x02\n\rMemoryService\x12?\n\x1aGetActiveInteractionMemory\x12\x0f.mem.MemRequest\x1a\x10.mem.MemResponse\x12\x32\n\rGetICanMemory\x12\x0f.mem.MemRequest\x1a\x10.mem.MemResponse\x12\x36\n\x11GetAgentAllMemory\x12\x0f.mem.MemRequest\x1a\x10.mem.MemResponse\x12\x36\n\x11GetChildAllMemory\x12\x0f.mem.MemRequest\x1a\x10.mem.MemResponse\x12\x34\n\x0fGetRelateMemory\x12\x0f.mem.MemRequest\x1a\x10.mem.MemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mem_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEMREQUEST']._serialized_start=19
  _globals['_MEMREQUEST']._serialized_end=197
  _globals['_MEMRESPONSE']._serialized_start=199
  _globals['_MEMRESPONSE']._serialized_end=257
  _globals['_MEMORYSERVICE']._serialized_start=260
  _globals['_MEMORYSERVICE']._serialized_end=558
# @@protoc_insertion_point(module_scope)
